server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticket-filight?useSSL=false&serverTimezone=UTC
    password: 543682
    username: kientran
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true